<?php

namespace Tests;

use Faker\Factory;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected $faker;
    protected object $response;

    /**
     * @throws \Throwable
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->login();

        $this->faker = Factory::create();
    }

    /**
     * @throws \Throwable
     */
    public function login()
    {
        $loginData = [
            'email' => 'admin@admin.com',
            'password' => '12345678'
        ];
        $login = $this->post(route('api.login'), $loginData, [
            'Accept' => 'application/json',
        ])
            ->assertStatus(200)
            ->assertJsonStructure(['access_token'])
            ->decodeResponseJson();
        $this->response = (object)$login->json();
    }
}
